
PRICE = 300000  #
DOWN = 0.3  #
DOWNPAYMENT = PRICE * DOWN
PRINCIPAL = PRICE * (1 - DOWN)
UNITS = 4  #
FURNITURE.PER.UNIT = 8000  #
FURNITURE = FURNITURE.PER.UNIT * UNITS
RENOVATION.PER.UNIT = 0  #
RENOVATION = RENOVATION.PER.UNIT * UNITS
INVEST = DOWNPAYMENT + RENOVATION + FURNITURE
APR = 0.038
YEAR = 30
MORTGAGE.PER.YEAR = PRINCIPAL * APR / (1 - 1/(1 + APR) ^ YEAR)
MORTGAGE.PER.MONTH = MORTGAGE.PER.YEAR / 12
TAXRATE = 0.023  #
TAX.PER.YEAR = PRICE * TAXRATE
TAX.PER.MONTH = TAX.PER.YEAR / 12

# Management Fee
WATER.PER.UNIT = 30
ELECTRICITY.PER.UNIT = 100
HEAT.PER.UNIT = 0
WIFI.PER.UNIT = 30
HOA = 0  #
MANAGEMENT.FEE = WATER.PER.UNIT * UNITS +
                 ELECTRICITY.PER.UNIT * UNITS +
                 HEAT.PER.UNIT * UNITS +
                 WIFI.PER.UNIT * UNITS +
                 HOA

# Return
OCCUPANCY = 18  #
RATE = 117  #
AIRBNB.INCOME = RATE * OCCUPANCY




# Monthly Net Income (Didn't count tax deduction)
NET.INCOME = AIRBNB.INCOME * UNITS -
             TAX.PER.MONTH -
             MANAGEMENT.FEE -
             MORTGAGE.PER.MONTH

NET.INCOME.PER.YEAR = NET.INCOME * 12

# Metrics
CAP.RATE = NET.INCOME.PER.YEAR / INVEST

print(CAP.RATE)
print(INVEST)
print(NET.INCOME.PER.YEAR)
